### ISSUE TITLE
[PE-D][Tester B] Unexpected behaviour in DelBookCommand 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-2/tp#229]
I was trying to delete all the books in MyBookshelf and tried this command:
* delbook b/ BOOKTITLEdelbook b/ BOOKTITLEdelbook b/ BOOKTITLEdelbook b/ BOOKTITLE

It looks like only the last `b/` prefix is taken as the input parameter.
Suggestion to either document this behaviour in the UG, or put in place additional checks in the code base.

![image.png](https://raw.githubusercontent.com/dayn-1/ped/main/files/e75dcf6b-40a8-4fc2-af91-805ace23add7.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: dayn-1/ped#9

**Comment by Ty-stan0417** [comment]
Fixed. Book title with " /b" is not allowed now.
