### ISSUE TITLE
[PE-D][Tester E] Addbook Command Allows Multiple b/ Declaration

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-2/tp#238]
# Description 

When executing `addbook b/Book1 b/Book2`, the command is processed but only Book2 was added into the library. Book1 was ignored and not added into the library list.

Not sure if this behaviour is intended, but could be mentioned in the UG. That is, allow users to know what happens if multiple `/b` are input into the command. 

# Alternative
1. An error could be throw and prompt users to only specify one book title.
2. Process all books beginning with `/b` i.e. allow multiple books to be added in one command execution.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: smolegz/ped#7

**Comment by Darkarche3** [comment]
Resolved  for duplicate issue #229
