### ISSUE TITLE
[PE-D][Tester B] Behaviour of books borrowed by contact after `DeleteCommand`

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-2/tp#242]
After executing `delete` of a contact, the books borrowed by the contact is not accounted for. 
Suggestion: Document the expected behaviour in the UG, or otherwise.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: dayn-1/ped#13

**Comment by Darkarche3** [comment]
Has been resolved under duplicate issue #239
