### ISSUE TITLE
[PE-D][Tester E] Donate Command Explanation in App

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-2/tp#252]
# Description 

When typing an invalid command `donate` in the interface, it says "edits the merit score of the person by the index number..." I feel that the error message could also explain the fact that a member from the contact list can add a book into the library list. Otherwise, a user might have the believe the main purpose of this command is to edit a person's merit score.

Moreover, when showing the parameters of the donate command, a clearer approach could be `b/[book-to-donate]`, rather than `b/[borrow]`. 

![photo_6089304194914827355_y.jpg](https://raw.githubusercontent.com/smolegz/ped/main/files/0bf5b9cc-f955-4082-9365-7f32ebba55f2.jpg)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: smolegz/ped#11

**Comment by Ty-stan0417** [comment]
This is fix in the future enhancement in the DG.
